kafkaSelector:
  type: env
  path: /app/kafka.config
  prefix: KAFKA_
interceptors:
  - name: loggingInterceptor
    pluginClass: io.conduktor.example.loggerinterceptor.LoggerInterceptorPlugin
    timeoutMs: 30000 #optional, default timeoutMs = 30s
    priority: 100
    config:
      - key: "loggingStyle"
        value: "obiWan"
      - key: "schemaRegistryUrl"
        value: "http://schema-registry:8081"
hostPortConfiguration:
  gatewayBindHost: 0.0.0.0
  gatewayHost: gateway
  portRange: 6969:6975
authenticationConfig:
  authenticatorType: NONE
  userPool: []
  # exponentialBackoff:
  #   multiplier: 2
  #   backoffMaxMs: 5000
  sslConfig:
    updateContextIntervalMinutes: 5
    keyStore:
      keyStorePath: None
      keyStorePassword: None
      keyPassword: None
      keyStoreType: jks
      updateIntervalMsecs: 600000
